# -*- coding: utf-8 -*-
"""main2 (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPrM-9mU7d_W8It7OLXAwW3H4w-eWVIa
"""

import plotly.graph_objects as go
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd
import pyreadr
import yfinance  as yf
import numpy as np
import scipy.stats
from scipy.stats import norm
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.stats.stattools import durbin_watson,jarque_bera
# altri possibili test da consultare per heteroskedasticità e autocorrelazione sono:
from statsmodels.stats.diagnostic import het_goldfeldquandt, het_white, acorr_ljungbox #heteroskedasticità
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from arch import arch_model
from math import sqrt
from sklearn.cluster import AgglomerativeClustering
import pandas as pd
from arch import arch_model
from statsmodels.stats.diagnostic import acorr_ljungbox
from scipy.cluster.hierarchy import dendrogram
from sklearn.metrics import silhouette_samples, silhouette_score

!pip install plotly scikit-learn pandas pyreadr yfinance numpy scipy matplotlib seaborn statsmodels arch scikit-fuzzy --quiet

"""IMPORT DEL DATASET FAMA-FRENCH"""

import os

print("Directory corrente:", os.getcwd())
print("File presenti:", os.listdir())

import pyreadr

file_path = r"C:\Users\vince\Downloads\fama_french_analysis-main\fama_french_analysis-main\FamaFrench_3Factors.RData"

# Legge il file .RData
result = pyreadr.read_r(file_path)

# Mostra gli oggetti contenuti nel file
print("Oggetti nel file:", result.keys())

# Prendi il dataset dei fattori (di solito si chiama così)
df = result["ff.factors"]

print(df.head())
print(df.info())

"""GESTIONE DEL DATASET FAMA-FRENCH"""

df = result["ff.factors"]
df.head()

# costruisco un metodo che calcola i rendimenti in eccesso

# def calcola_rendimenti(df,Rm,Rf):
#      df["Excess_return"] = Rm-Rf
#      return df

# df_2 = calcola_rendimenti(df,df["Rm"],df["RF"])

# df_2.head()

df["Date"] = pd.to_datetime(df["Date"])

start_date = "2013-06-19"
end_date = "2023-06-19"

type(df["Date"])

df2 = df[
    (df["Date"] >= pd.to_datetime(start_date)) &
    (df["Date"] <= pd.to_datetime(end_date))
]

df2.head()

"""CHECK MISSING VALUE"""

df2.isna().sum()

"""CALCOLO DEI RENDIMENTI SWISS RE DB"""

ticker = "SREN.SW"
px = yf.download(
    ticker,
    start=start_date,
    end=end_date,
    auto_adjust=False
)

px.head()

"""PROBLEMA: LE COLONNE SONO MULTIINDEX MENTRE L'INDICE QUI SONO LE DATE. PER POTER MERGARE CORRETTAMENTE I DUE DATASET E' NECESSARIO CREARE UNA STRUTTURA PER ENTRAMBI I DATASET CHE PERMETTA POI DI FARE IL MERGE"""

px.columns
px.index

h0=[(4,"Hello"),(3,"Sorry")]
isinstance(h0, dict)

"""CORREZIONE DELL'INDICE COLONNA. Usiamo il metodo isinstance in quanto permette di capire il tipo di oggetto essendo le colonne del db swissre MultiIndex"""

if isinstance(px.columns,pd.MultiIndex):
    px.columns = px.columns.get_level_values(0)

px.columns

"""ORA LE COLONNE APPAIONO CORRETTE"""

px.head()

"""CALCOLO DEI LOG RETURN  ADJUSTED"""

# facendo in questo modo otteniamo un oggetto di tipo Series. Una volta ottenuto va convertito in data frame con il metodo to_frame(name = "Nome della colonna")

swissre = np.log(px["Adj Close"]/ px["Adj Close"].shift(1))

swissre = swissre.dropna().to_frame(name="Log_Returns")

"""CHECK DEL TIPO:
Ritorna un pandas.core.frame.DataFrame
"""

swissre.head()
# type(swissre)

"""LAVORIAMO ORA SULL'INDICE DATE PER PORTARLO COME COLONNA E MERGARLO CON L'ALTRO.
Prima di fare il merge è necessario eliminare la parte oraria e utilizziamo cosi il metodo .dt.normalize
"""

swissre = swissre.reset_index()

swissre["Date"] = pd.to_datetime(swissre["Date"]).dt.normalize()

swissre.head()

"""DATASET MERGED"""

merged_data = pd.merge(
    swissre,
    df2,
    on="Date",
    how="inner"
)

merged_data.head()

"""A questo punto andiamo a ridefinire l'indice delle date con il metodo set_index"""

merged_data = merged_data.set_index("Date")

merged_data.head()

"""MERGED DATASET"""

merged_data.head()

#DatetimeIndex
# merged_data.index

# merged_data.columns

"""A QUESTO PUNTO DEFINIAMO UN METODO PER CALCOLARE GLI EXCESS RETURN SIA DI SWISS RE SIA DI QUELLO DEL PORTAFOGLIO DI MERCATO"""

def excess_return(asset_return,risk_free):
    return asset_return-risk_free

# creo una nuova colonna nel dataset merge con i rendimenti in eccesso di swiss re
merged_data["Swiss_Excess_Return"]=excess_return(asset_return=merged_data["Log_Returns"],risk_free=merged_data["RF"])

# stessa cosa con il rendimento di mercato

merged_data["Market_Return"] = excess_return(asset_return=merged_data["Rm"],risk_free=merged_data["RF"])

merged_data["Market_Return"].shape
merged_data["Swiss_Excess_Return"].shape

merged_data["Market_Return"].head()

merged_data["Swiss_Excess_Return"].head()

merged_data["Market_Return"].shape
merged_data["Swiss_Excess_Return"].shape

"""STATISTICHE DESCRITTIVE DEL DATASET"""

merged_data.index

# Non ci sono valori mancanti nella serie

merged_data.isna().sum()

# Statistiche descrittive del dataset

merged_data[["Log_Returns","Rm"]].describe()

# andiamo a vedere la shape del nostro db.

merged_data.shape  # 2461 righe e 6 colonne

"""    CALCOLO DEGLI EXCESS RETURN  PER SWISS RE E PER QUELLI DI MERCATO
    
"""

def calcolo_rendimenti_eccesso(merged_data):
    return merged_data["Log_Returns"]- merged_data["Rm"]

"""PLOT DEI RENDIMENTI:

ANDIAMO A FARE UN'ANALISI GRAFICA DELLA DISTRIBUZIONE DEI LOG-RENDIMENTI E DEL RENDIMENTO DI MERCATO
"""

calcolo_corr = merged_data[["Rm","Log_Returns"]].corr()

print(calcolo_corr)

sns.heatmap(calcolo_corr, vmin=-1,vmax=1,fmt=".2f",annot=True)
# annot parametro utile per stampare la correlazione fra gli asset quando sono cosi pochi. Essendo solo coppie di variabili possiamo passare direttamente allo scatterplot

merged_data.head()

calcolo_corr2 = merged_data[["Rm","Log_Returns","SMB","HML"]].corr()

sns.heatmap(calcolo_corr2, vmin=-1,vmax=1,annot=True)

"""INTERESSANTE NOTARE LA PRESENZA DI ALTISSIMI E BASSISSIMI RENDIMENTI DURANTE LA PANDEMIA. SI POTREBBE USARE UN MODELLO  HMM-GARCH PER CLASSIFICARE LA VOLATILITA' IN QUANTO I GARCH NASCONO CON L'IDEA DI MODELLARE VOLATILITY-CLUSTER."""

sns.scatterplot(merged_data[["Log_Returns","Rm"]])

sns.regplot(
    data=merged_data,
    x="Rm",
    y="Log_Returns",
    scatter_kws={"color": "blue"},
    line_kws={"color": "red"}
)

"""FIT DEL MODELLO considerando come covariata solo il rendimento di mercato"""

X = merged_data["Market_Return"]
y = merged_data["Swiss_Excess_Return"]

X = sm.add_constant(X)

modello = sm.OLS(y,X)

result = modello.fit()

print(result.summary())

print(f"Parametri stimati: {result.params}")
print(f"Standar_Errors: {result.bse}")

"""Dai risultati si evince che l' R-quadro Adjusted non è molto alto.

Andiamo a fittare un modello anche con altre variabili esplicative
"""

merged_data.columns

X_1 = merged_data[["Market_Return","SMB","HML"]]

y_1 = merged_data["Swiss_Excess_Return"]

X_1 = sm.add_constant(X_1)

modello_full = sm.OLS(y_1,X_1)

risultato_full = modello_full.fit()

print(risultato_full.summary())

"""Valutazione della presenza di multicollinearità attraverso il test VIF dovuto alla presenza di un cond. No. >100. Oppure valutare attraverso la radice quadrato del rapporto degli autovalori della matrice (XX^-1) ha un valore minore di 100.

Interpretazione del VIF:

1.   Valori => 5 multinearità problematica per il modello
2.   Valori (1-5) mutlinearità tollerabile


"""

from statsmodels.stats.outliers_influence import variance_inflation_factor

X = merged_data[["Market_Return", "SMB", "HML"]]
X = sm.add_constant(X)

vif_df = pd.DataFrame()
vif_df["variable"] = X.columns
vif_df["VIF"] = [variance_inflation_factor(X.values, i)
                 for i in range(X.shape[1])]

print(vif_df)

"""OCCORE FARE DEI TEST STATISTICI PER CAPIRE SE LE IPOTESI SOTTOSTANTI IL MODELLO DI REGRESSIONE LINEARE SONO VERIFICATE.
In particolare, verranno condotti dei test su heteroschedasticità, autocorrelazione e test sulla normalità dei residui.
L'utilizzo di test diagnostici permette di capire se gli stimatori dei parametri beta ottenuti dal modello siano BLUE. (Best linear umbiesed estimator)

Autocorrelazione dei residui- DURBIN WATSON TEST

Il durbin watson test è un test statistico che permette di capire se c'è autocorrelazione tra i residui del modello stimato.
Se:
DW è approssimativamente 2 allora non c'è autocorrelazione
DW <2 autocorrelazione positiva
DW >2 autocorrelazione negativa
"""

dw = durbin_watson(result.resid)

print(dw)

"""AUTOCORRELAZIONE
Data una serie storica temporale come quella che stiamo analizzando, la funzione di autocorrelazione misura quanto l'elemento della serie Xt, abbia una relazione con un istante di tempo precedente X(t-h). L'analisi dell'andamento della funzione di correlazione al variare di questo h è di fondamentale importanza per stabilire la "memoria" della serie storica. In poche parole andiamo a vedere quanto di ciò che vediamo all'istante t risenta di cio che è successo a (t-h)

AUTOCORRELAZIONI GLOBALI

La funzione acf ritorna una tupla di array, in questo caso potrebbe essere utile scegliere un certo numero di " trading days " per vedere se ci sono correlazione con i valori ritardati dei residui. Questo ci potrebbe permettere di fittare dei modelli autoregressivi o di capire piu in generale meglio l'andamento dell' autocorrelazione. Si potrebbe sfruttare l'informazione sul numero di lag p da inserire per fittare una regressione ausiliaria e costruire una statistica test come nel caso di Godfey
"""

acf_prova = acf(risultato_full.resid, nlags = 10, qstat= True, fft=False)

"""Uno strumento utile per valutare se la serie è stazionaria potrebbe essere il correlogramma, questo rappresenta un grafico a barre che riporta i coefficienti di correlazione per ogni k della serie sull'asse delle ascisse. Affinchè non ci sia una forte relazione tra i periodi le barre dovrebbero stare entro le bande con un andamento variabile"""

plt.figure(figsize=(16,8))
plot_acf(risultato_full.resid, lags=10)
plt.show()

"""ANALISI DELLA NORMALITA'. Un aspetto importante da tenere in considerazione riguarda il fatto che nel 2020 ci sono stati degli spike dovuti alla pandemia. Questo fatto potrebbe comportare delle code piu pesanti della distribuzione normale. Si potrebbe usare una dummy variable con valore 1 se il periodo è 2020, 0 altrove. Si potrebbe poi rieseguire il test di jarque e bera per vedere se l'ipotesi di normalità possa essere accettata sotto H0."""

import pandas as pd

df.index = pd.to_datetime(df.index)

df["COVID"] = (
    (df.index >= "2020-02-24") &
    (df.index <= "2020-06-30")
).astype(int)

"""Introduciamo la variabile dummy per tenere in considerazione l'effetto del covid nel modello di regressione"""

import datetime
start_date = datetime.datetime(2013,6,19)
end_date = datetime.datetime(2023,6,19)

merged_data["COVID"] = (
    (merged_data.index >= "2020-02-24") &
    (merged_data.index <= "2020-06-30")
).astype(int)

"""Controllo che la colonna che include la dummy variable sia stata creata correttamente

"""

merged_data.columns.view()

merged_data["COVID"].isna().sum()

(df["COVID"]==1).sum()

"""L'analisi di regressione aggiungendo la variabile Covid come regressore ha evidenziato, aggiungendo la dummy Covid, il modello non ha aumentato la capacità di spiegare i rendimenti;"""

merged_data.columns

X_2 = merged_data[["Market_Return","SMB","HML","COVID"]]

y_2 = merged_data["Swiss_Excess_Return"]

X_2 = sm.add_constant(X_2)

modello_full = sm.OLS(y_2,X_2)
risultato_full_1 = modello_full.fit()

print(risultato_full_1.summary())

"""Fitting del modello OLS con la presenza del termine d'interazione.
L'aggiunta nel modello anche del termine di interazione ci permette di valutare se come il rendimento di mercato impatti il portafoglio nel periodo Covid.

"""

print(risultato_full.summary())
print("\n" + "="*80 + "\n")  # separatore
print(risultato_full_1.summary())

"""Il modello OLS evidenzia come il termine d'interazione sia statisticamente significativo, il portafoglio quindi diventa più sensibile all'eccesso di rendimento del mercato durante il periodo Covid. L'R^2 aumenta maggiormente rispetto all'introduzione della sola variabile dummy.

"""

#Calcolo del termine di interazione Covid x (Rm-Rf)
merged_data["Covid_Market"] = merged_data["Market_Return"] * merged_data["COVID"]

merged_data.columns

X_3 = merged_data[["Market_Return","SMB","HML","COVID","Covid_Market"]]

y_3 = merged_data["Swiss_Excess_Return"]

X_3 = sm.add_constant(X_3)

modello_full = sm.OLS(y_3,X_3)
risultato_full_2 = modello_full.fit()

print(risultato_full_2.summary())

"""Jarque bera con dummy variable e termine d'interazione"""

output = jarque_bera(risultato_full_2.resid)
print(output)

# Scrivo un metodo che prende in input il p-value e alpha e ritorna il risultato del test

def  test_statistico(alpha,p_value):
    if alpha > p_value:
        print("Rigettiamo H0")
    else:
        print("Accettiamo H0 in quanto il p-value è maggiore di alpha")


test_statistico(alpha=0.05,p_value=output[1])

risultato_full_2.params

"""Passaggi da verificare:
- Fitting modello OLS e osservare non ci sia multicollinearità elevata
- Valutazione omeoschedasticità degli errori attraverso la valutazione del F-statistic ed LM-statistic    (H0 errori omeoschedastici)
- Presenza di eteroschedasticità -> soluzione: mantenere i coefficienti OLS (non distorti)
e utilizzare gli errori standard robusti o utilizzare un modello pesato.

"""

# Valutiamo l'eteroschedasticità con il test di Breusch-Pagan
from statsmodels.stats.diagnostic import het_breuschpagan

residui = risultato_full_2.resid
X_bp   = risultato_full_2.model.exog   # stessa X usata nel fit

bp_test = het_breuschpagan(residui, X_bp, robust=False)
lm_stat, lm_pvalue, f_stat, f_pvalue = bp_test
print("LM stat:", lm_stat, "LM p:", lm_pvalue)
print("F stat:", f_stat, "F p:", f_pvalue)

# Estendiamo il test di Breusch-Pagan includendo termini non lineari e interazioni
Z = pd.DataFrame({
    "const": 1.0,
    "Market": merged_data["Market_Return"],
    "SMB": merged_data["SMB"],
    "HML": merged_data["HML"],
    "COVID": merged_data["COVID"],
    "Covid_Market": merged_data["Covid_Market"],
    # termini non lineari / interazioni aggiuntive per la varianza
    "Market2": merged_data["Market_Return"]**2,
    "HML2": merged_data["HML"]**2,
    "Market_HML": merged_data["Market_Return"] * merged_data["HML"],
})

from statsmodels.stats.diagnostic import het_breuschpagan

residui = risultato_full_2.resid
bp_test_ext = het_breuschpagan(residui, Z.values)

lm_stat, lm_pvalue, f_stat, f_pvalue = bp_test_ext
print("LM stat:", lm_stat, "LM p:", lm_pvalue)
print("F stat:", f_stat, "F p:", f_pvalue)

"""Il test ha come risultato il rifiuto di H0 (omeoschedasticità degli errori), è presente quind iun eteroschedasticità dei residui dovuta all'effetto odei diversi regressori fittati dal modello OLS"""

X_bp.view()

"""Controllare visivamente quando i rendimenti si discostano da 3 la varianza"""

residui = risultato_full.resid
outliers = np.abs(residui) > 3*residui.std()  # spike oltre 3 deviazioni standard
print(merged_data.index[outliers])

"""Sembra che dall'analisi della cdf empirica ci siano degli outlier"""

result.resid.mean()

sns.histplot(result.resid, kde = True, bins = 30)

sm.qqplot(result.resid, line ="r")
plt.show()

resid_sorted = np.sort(result.resid.values)

n = len(resid_sorted)
p_s = np.linspace(0.5/n, 1 - 0.5/n, n)

plt.plot(resid_sorted, p_s, 'g.')
plt.xlabel("residual_cdf")
plt.ylabel("ECDF")
plt.show()

"""Jarque bera test è un test in cui si testano due ipotesi congiuntamente. Sotto l'ipotesi nulla la simmetria è zero mentre la kurtosi deve essere 3. Questo per le proprietà della funzione di densità della normale. Fissato l'alpha possiamo confrontarlo con il p-value. Tanto piu il p-value è piccolo tanto piu andiamo a rifiutare l'ipotesi di normalità. Tuttavia, è possibile sempre sfruttare il teorema del limite centrale con un n sufficientemente grande possiamo accettare l'approssimazione dei residui alla normale standard. (Quanto deve essere grande n?)

Leggendo la documentazione il metodo jarque_bera ritorna un array con i seguenti output:
- JB che indica la statistica test
- JBpv che indica il pvalue del test statistico
- l'asimmetria della distribuzione
- la kurotis della distribuzione
"""

output = jarque_bera(result.resid)
print(output)

# Scrivo un metodo che prende in input il p-value e alpha e ritorna il risultato del test

def  test_statistico(alpha,p_value):
    if alpha > p_value:
        print("Rigettiamo H0")
    else:
        print("Accettiamo H0 in quanto il p-value è maggiore di alpha")


test_statistico(alpha=0.05,p_value=output[1])

"""I parametri disp e update_freq. Disp controlla cosa viene stampato mentre viene fatta la stima mentre update freq in fit, regola il numero di iterazioni nella stima dei parametri della log likelihood. Questo perchè per ipotesi, nel modello specificato i rendimenti in eccesso di swiss sono distribuiti come una normale standard.

Fit dei modelli Garch (1,1) e GJR (1,1,1) con distribuzione normale degli errori.
"""

y_garch = merged_data["Swiss_Excess_Return"]

y_garch.head()


# fit garch(1,1)

spec = arch_model(y_garch,
           mean="constant",
           vol="GARCH",
           p=1,
           q=1,
           dist="normal",
           rescale=False)

garch_mod = spec.fit()

print(garch_mod.summary())

y_garch_t = merged_data["Swiss_Excess_Return"]

y_garch_t.head()


# fit garch(1,1)

spec = arch_model(y_garch_t,
           mean="constant",
           vol="GARCH",
           p=1,
           q=1,
           dist="normale",
           rescale=True)

garch_mod_t = spec.fit()

print(garch_mod_t.summary())

y_garch_t_1 = merged_data["Swiss_Excess_Return"]
y_garch_t_mean= y_garch_t.mean()
y_garch_t_sd= y_garch_t.std()
y_garch_t1 = (y_garch_t - y_garch_t_mean)/ y_garch_t_sd
print(f"Y_standard:{y_garch_t1}")

"""Modellazione degli errori attraverso i modelli Garch (1,1) GJR (1,1,1) con distribuzione degli errori t di student."""

# fit garch(1,1)

spec_1 = arch_model(y_garch_t1,
           mean="constant",
           vol="GARCH",
           p=1,
           q=1,
           dist="t",
           rescale=False)

garch_mod_t_1 = spec_1.fit()

print(garch_mod_t.summary())

#AIC
garch_mod_t_1.aic
# BIC
garch_mod_t_1.bic

from arch import arch_model

y_garch_t_1 = merged_data["Swiss_Excess_Return"]

# Specifica GJR-GARCH(1,1) con Student-t
spec_gjr = arch_model(
    y_garch_t_1,
    mean="constant",
    vol="GARCH",
    p=1,
    o=1,  # termine asimmetrico
    q=1,
    dist="t",
    rescale=False
)

# Fit
gjr_mod = spec_gjr.fit(update_freq=5, disp='off')
# Summary
print(gjr_mod.summary())

from scipy.optimize import minimize

# Metodi disponibili in scipy.optimize.minimize
print(minimize.__doc__.split('method :')[1].split('\n')[0])

y_garch_n_3 = merged_data["Swiss_Excess_Return"]

# Specifica GJR-GARCH(1,1) con Student-t
spec_gjr = arch_model(
    y_garch_n_3,
    mean="constant",
    vol="GARCH",
    p=1,
    o=1,  # termine asimmetrico
    q=1,
    dist="normal",
    rescale=False
)

# Fit
gjr_mod_1 = spec_gjr.fit(update_freq=5, disp='final')

# Summary
print(gjr_mod_1.summary())

y_garch_t = merged_data["Swiss_Excess_Return"]

y_garch_t.head()


# fit garch(1,1)

spec = arch_model(y_garch_t,
           mean="constant",
           vol="GARCH",
           p=1,
           q=1,
           dist="t",
           rescale=True)

garch_mod_t = spec.fit()

print(garch_mod_t.summary())

omega_t=garch_mod_t_1.params["omega"]
alpha_t=garch_mod_t_1.params["alpha[1]"]
beta_t=garch_mod_t_1.params["beta[1]"]
garch_mod_t_1.resid[1]

len(garch_mod_t_1.resid)

len(garch_mod_t_1.conditional_volatility)

print(garch_mod_t_1._volatility)

merged_vol_res=pd.DataFrame({
    "Volatility": garch_mod_t_1.conditional_volatility,
    "Residuals": garch_mod_t_1.resid

})

merged_vol_res.head()

sigma_1= omega_t/(1-alpha_t-beta_t)
print(f"Long-Run Variance: {sigma_1}")

sigma_2=omega_t+alpha_t*(merged_vol_res["Residuals"][0])**2+beta_t*(merged_vol_res["Volatility"][0])**2
print(f"One-step ahead Variance: {sqrt(sigma_2)}")

merged_vol_res["Volatility"]["2013-06-20"]

y_garch_t.mean()

"""Plot della varianza condizionata del modello Garch(1,1)"""

plt.plot(garch_mod_t.conditional_volatility)



"""Plot dei residui del modello Garch(1,1) con distribuzione Student-t."""

plt.plot(garch_mod_t.resid)

garch_mod_t.params

merged_data.tail()

garch_forecast = garch_mod.forecast(horizon=2)

print(garch_forecast.variance)

"""Print dei parametri stimati dal modello garch e visualizzazione della varianza di lungo periodo."""

print(f"omega_stimato: {garch_mod.params["omega"]}")
print(f"alpha: {garch_mod.params["alpha[1]"]}")
print(f" beta: {garch_mod.params["beta[1]"]}")

# ritornano 3 float
omega = garch_mod.params["omega"]
alpha = garch_mod.params["alpha[1]"]
beta = garch_mod.params["beta[1]"]

long_run_variance = omega/(1-alpha-beta)
print(long_run_variance)

long_run_volatility = print(sqrt(long_run_variance))

"""Download di 30 titoli a maggior capitalizzazione facente parte del mercato azionario americano e creazione della funzione per ottenere i log rendimenti."""

symbols=[# Information Technology (6)
    "AAPL", "MSFT", "NVDA", "AMD", "INTC", "ADBE",
    # Financials (4)
    "JPM", "BAC", "GS", "WFC",
    # Industrials (5)
    "CAT", "BA", "DE", "GE", "HON",
    # Consumer Discretionary (4)
    "TSLA", "AMZN", "HD", "MCD",
    # Healthcare (3)
    "JNJ", "PFE", "MRK",
    # Energy (3)
    "XOM", "CVX", "SLB",
    # Communication Services (5)
    "GOOGL", "META", "NFLX", "T", "VZ"]
start_date = "2013-06-19"
end_date = "2023-06-19"

def calcolo_rendimenti(symbols, start_date, end_date):
    price= yf.download(tickers=symbols,start=start_date,end=end_date,auto_adjust=False)
    returns = np.log(price["Adj Close"]/ price["Adj Close"].shift(1))
    returns = returns.dropna()
    return returns

"""Creazione del dataframe con i log rendimenti dei 30 titoli e del dataframe con i parametri del modello Garch (1,1)."""

rendimenti=calcolo_rendimenti(symbols, start_date, end_date)
rendimenti.head()

# Lista per salvare i parametri
risultati = []

for col in rendimenti.columns:
    spec = arch_model(
        rendimenti[col],
        mean="constant",
        vol="GARCH",
        p=1,
        q=1,
        dist="t",
        rescale=False
    )
    garch_mod_col = spec.fit(disp="off")
    db_parametri = garch_mod_col.params

    # Salvo i parametri in un DataFrame
    df_col = pd.DataFrame({
        "Omega": [db_parametri["omega"]],
        "Alpha": [db_parametri["alpha[1]"]],
        "Beta": [db_parametri["beta[1]"]],
        "Nu": [db_parametri["nu"]]
    }, index=[col])

    risultati.append(df_col)

# Concateno tutto
db_parametri_finale = pd.concat(risultati)
print(db_parametri_finale)

# Lista per salvare i dati di tutti i ticker
risultati = []

for ticker in rendimenti.columns:
    # Fit GARCH(1,1) con distribuzione t
    spec = arch_model(rendimenti[ticker], mean="constant", vol="GARCH", p=1, q=1, dist="t", rescale=False)
    res = spec.fit(disp="off")

    # Estrazione parametri
    omega = res.params["omega"]
    alpha = res.params["alpha[1]"]
    beta  = res.params["beta[1]"]
    nu    = res.params["nu"]

    # Residui standardizzati
    resid_std = res.std_resid

    # Test di Ljung-Box sui residui standardizzati, lag 10
    lb_test = acorr_ljungbox(resid_std**2, lags=20, return_df=True)
    p_val = lb_test['lb_pvalue'].iloc[-1]  # prendo il p-value del lag 10


    # Salvo tutti i dati in un dizionario
    dati = {
        "Ticker": ticker,
        "Omega": omega,
        "Alpha": alpha,
        "Beta": beta,
        "Nu": nu,
        "LjungBox_pvalue": p_val,
    }

    risultati.append(dati)

# Creo il DataFrame finale
db_parametri_finale = pd.DataFrame(risultati)
db_parametri_finale.set_index("Ticker", inplace=True)

# Controllo
print(db_parametri_finale.head())

# Lista per salvare i dati di tutti i ticker
risultati_cluster = []

for ticker in rendimenti.columns:
    # Fit GARCH(1,1) con distribuzione t
    spec = arch_model(rendimenti[ticker], mean="constant", vol="GARCH", p=1, q=1, dist="t", rescale=False)
    res = spec.fit(disp="off")

    # Estrazione parametri
    omega = res.params["omega"]
    alpha = res.params["alpha[1]"]
    beta  = res.params["beta[1]"]
    nu    = res.params["nu"]



    # Salvo tutti i dati in un dizionario
    dati = {
        "Ticker": ticker,
        "Omega": omega,
        "Alpha": alpha,
        "Beta": beta,
        "Nu": nu,
    }

    risultati_cluster.append(dati)

# Creo il DataFrame finale
db_parametri_cluster = pd.DataFrame(risultati_cluster)
db_parametri_cluster.set_index("Ticker", inplace=True)

# Controllo
print(db_parametri_cluster.head())

"""Check per controllare la media e std dei parametri stimati e conseguente utilizzo della funzione Standard Scaler."""

media_parametri=db_parametri_cluster.mean()
std_parametri=db_parametri_cluster.std()
print(media_parametri)
print(std_parametri)

"""Standardizzazione con la classe StandardScaler e attraverso la creazione di una funzione apposita. La standardizzazione è ottenuta sottraendo la media e dividendo per la deviazione standard, il suo utilizzo è fondamentale per poter confrontare i parametri ed evitare che i valori outlier inficino l'analisi."""

X=db_parametri_cluster[["Omega","Alpha","Beta","Nu"]].values

"""Standardizzazione dei parametri del modello Garch(1,1) con una funzione creata ad hoc."""

def db_scalato(db_parametri_cluster):
    for col in db_parametri_cluster.columns:
        mean_col= db_parametri_cluster[col].mean()
        std_col= db_parametri_cluster[col].std()
        db_parametri_cluster[col] = (db_parametri_cluster[col]-mean_col)/std_col
    return db_parametri_cluster

"""Creazione del dataframe con i parametri standardizzati per il seguente utilizzo negli algoritmi di clustering."""

db_cluster=db_scalato(db_parametri_cluster)

db_cluster.head()

"""Analisi degli algoritmi di clustering, uso del modello KMeans e scelta del numero di cluster attraverso il metodo elbow."""

metrica=[]
for n in range(1,11):
    algorithm=KMeans(n_clusters=n, init='k-means++', n_init=10, max_iter=300, random_state=111, algorithm='elkan', tol=0.0001)
    algorithm.fit(db_cluster)
    metrica.append(algorithm.inertia_)

print(metrica)

"""Il grafico seguente mostra come varia la distanza di ogni punto dal centroide del cluster al variare del numero dei cluster, la figura seguente ci permette di determinare come numero dei cluster ottimale il valore n_cluster=3."""

plt.figure(1, figsize=(18, 8))
plt.plot(np.arange(1,11), metrica, marker="o")
plt.plot(np.arange(1,11), metrica, marker="_", alpha=0.5)
plt.xlabel("Numero di cluster")
plt.ylabel("Metrica")
plt.title("Ebow method")
plt.show()

kmeans_cluster=KMeans(n_clusters=3, init='k-means++', n_init=10, max_iter=300, random_state=111, algorithm='elkan', tol=0.0001)
kmeans_cluster.fit(db_cluster)
labels=kmeans_cluster.labels_

"""Visualizzazione dell'assegnazione dei titoli ad ogni clsuter."""

print((labels))

"""Visualizzazione di come vengono assegnati i diversi titoli ad ogni cluster."""

db_cluster["cluster"]=labels

db_cluster.head(30)

db_cluster_media=db_cluster.groupby("cluster").mean()
db_cluster_std=db_cluster.groupby("cluster").std()
print(db_cluster_media)
print(db_cluster_std)

"""Come notiamo dal codice sopra, i parametri medi per ogni cluster risultano influenzati dalla standardizzazione sugli stessi parametri, pertanto quest'ultimi vanno riportati su scala normale."""

media_alpha=db_cluster['Alpha'].groupby(db_cluster['cluster']).mean()
media_omega=db_cluster['Omega'].groupby(db_cluster['cluster']).mean()
media_beta=db_cluster['Beta'].groupby(db_cluster['cluster']).mean()
pd_dataframe_media=pd.DataFrame({
    "Alpha": media_alpha,
    "Omega": media_omega,
    "Beta": media_beta
})
print(pd_dataframe_media)

def destandardizzazione(dati,media,std):
    parametri_scala_normale= (dati*std)+media
    return parametri_scala_normale

dataframe_kmeans_destandard=destandardizzazione(pd_dataframe_media,media_parametri,std_parametri)
print(dataframe_kmeans_destandard)

"""Dalla media destandardizzata dei parametri per ogni cluster vediamo come le condizioni di stazionarietà vengono rispettate. Il primo cluster presenta una reattività agli schock recenti molto elevata e persistente differentemente dagli ultimi due cluster che presentano una persistenza della volatilità nel tempo maggiore."""

parametri_new=destandardizzazione(db_cluster,media_parametri,std_parametri)
print(parametri_new)

db_parametri_cluster["labels"]=labels

"""Visualizzazione in 3D del posizionamento dei titoli in base ai parametri dei modelli Garch stimati."""

import plotly.graph_objects as go

trace = go.Scatter3d(
    x=db_cluster['Omega'],
    y=db_cluster['Alpha'],
    z=db_cluster['Beta'],
    mode='markers',
    marker=dict(
        color=db_cluster['cluster'],  # label K-Means
        size=6,
        opacity=0.8
    )
)

fig = go.Figure(data=[trace])
fig.update_layout(
    title="Clusters (Omega, Alpha, Beta)",
    scene=dict(
        xaxis_title="Omega",
        yaxis_title="Alpha",
        zaxis_title="Beta"
    )
)
fig.show()

"""Confronto con un'altra metrica di agglomeritve clustering (Metodo Ward), che a differenza del precedente metodo punta a creare cluster omogenei fra loro e distaccati dagli altri cluster. Il calcolo della distanza si basa sulla misura di distanza euclidea e minimizza l'aumento della varianza interna quando vengono uniti due cluster.

I risultati del modello di clustering sono visualizzati attraverso un dendogramma, che rappresenta una visualizzazione grafica ad albero nel clustering gerarchico e non serve specificare a priori il numero di cluster.
"""

from scipy.cluster.hierarchy import dendrogram

def plot_dendrogram(model, labels=None, **kwargs):
    """
    Plot dendrogram per AgglomerativeClustering con etichette ticker.

    Parameters:
    - model: fitted AgglomerativeClustering
    - labels: list of ticker (es. db_rendimenti.columns.tolist())
    - **kwargs: passed to dendrogram (es. truncate_mode, p)
    """
    # Conta campioni sotto ogni nodo
    counts = np.zeros(model.children_.shape[0])
    n_samples = len(model.labels_)
    for i, merge in enumerate(model.children_):
        current_count = 0
        for child_idx in merge:
            if child_idx < n_samples:
                current_count += 1  # leaf
            else:
                current_count += counts[child_idx - n_samples]
        counts[i] = current_count

    # Crea linkage matrix
    linkage_matrix = np.column_stack([model.children_, model.distances_, counts]).astype(float)

    # Plot dendrogramma con labels
    dendrogram(linkage_matrix, labels=labels, **kwargs)

tick= rendimenti.columns
plt.figure(figsize=(16, 8))
plt.title("Dendogramma Agglomerative Clustering- Ward")
plot_dendrogram(clustering_ward,
                labels=tick,
                leaf_rotation=90,      # Ruota etichette di 90°
                leaf_font_size=10,
                         # Riduce dimensione font
)

"""Utilizziamo l'indice di silhouette per avere un secondo confronto per valutare il numero ottimale di cluster, tale indice medio restituisce i valori per numero di cluster che punta a massimizzare la distanza dagli altri cluster e minimizzare la distanza interna.
I risultati ottenuti mostrano come una specificazione di 6 cluster sarebbe ottimale per il suddetto modello di clustering.
"""

scores = []

for k in range(2, 12):
    model = AgglomerativeClustering(n_clusters=k, linkage="ward")
    labels = model.fit_predict(db_cluster)
    score = silhouette_score(db_cluster, labels)
    scores.append(score)
    print(f"k={k}, silhouette={score:.3f}")

plt.figure()
plt.plot(range(2, 12), scores, marker='o')
plt.xlabel("Numero di cluster")
plt.ylabel("Silhouette media")
plt.title("Metodo silhouette – Ward")
plt.show()

clustering_ward=AgglomerativeClustering(n_clusters=3, linkage="ward", metric="euclidean",  compute_distances=True)
model=clustering_ward.fit(db_cluster)
labels_ward=clustering_ward.labels_

print(labels_ward)  # [0, 0, 1, 2, 0, ...]

df_cluster = pd.DataFrame(db_cluster)  # Converte in DataFrame

# Aggiunge colonna labels
df_cluster['cluster'] = labels_ward

# Calcola medie per cluster e feature
medie_cluster = df_cluster.groupby('cluster').mean()
print(medie_cluster)

cluster_3_titoli = df_cluster[df_cluster['cluster'] == 3].index.tolist()
print(cluster_3_titoli)

# Destandardizzazione dei parametri per conforntare le medie dei cluster ottenuti tramite algoritmo Ward

dataframe_standardizzato_ward=destandardizzazione(medie_cluster,media_parametri,std_parametri)

dataframe_standardizzato_ward.drop("labels",axis=1,)

"""Introduzione dell'algoritmo di clustering fuzzy-Kmeans che permette una classificazione soft con l'assegnazione del titolo ad ogni cluster con diverso grado di appartenenza, per adoperare un confronto più completo e senza forzare la suddivsione dei titoli."""

pip install scikit-fuzzy

import skfuzzy as fuzz

"""Calcolo dell'indice di silhouette per un valore di fuzziness che appartiene ad un range(1.2-2.5), questo valore permette di specificare l'appartenza o meno ad un singolo cluster, maggiore è il valore del parametro m, più il titolo può avere un grado di assegnazione distribuito fra i diversi cluster. Seppure il valore di silhouette sia maggiore con m=1.2, si tende a preferire una suddivisione più bilanciata dei titoli nei seguenti cluster e quindi viene utilizzato un valore m=2, con un valore k=3 cluster."""

# Range parametri
k_range = range(2, 9)  # Numero cluster
m_range = [1.2, 1.5, 2.0, 2.5]  # Fuzziness

# Dizionario per salvare scores
fuzzy_scores = {m: [] for m in m_range}

print("FUZZY C-MEANS - Silhouette Scores:")
print("k\t|\tm=1.2\tm=1.5\tm=2.0\tm=2.5")
print("-" * 40)

# Calcolo silhouette per ogni combinazione k-m
for k in k_range:
    row_scores = []
    for m in m_range:
        # Fuzzy C-Means
        cntr, u, u0, d, jm, p, fpc = fuzz.cmeans(
            db_cluster.T,
            c=k,
            m=m,
            error=0.005,
            maxiter=300
        )

        # Hard clustering per silhouette
        labels_hard = np.argmax(u, axis=0)

        # Silhouette score
        score = silhouette_score(db_cluster, labels_hard)
        fuzzy_scores[m].append(score)
        row_scores.append(score)

        print(f"{k}\t|\t{score:.3f}", end='')

    print()  # Nuova riga

# PLOT
plt.figure(figsize=(12, 8))

# Singole linee per ogni m
colors = ['blue', 'red', 'green', 'orange']
for i, m in enumerate(m_range):
    plt.plot(k_range, fuzzy_scores[m], 'o-',
             linewidth=3, markersize=10,
             label=f'm={m}',
             color=colors[i],
             alpha=0.8)

# Miglior k per ogni m
for i, m in enumerate(m_range):
    best_k = np.argmax(fuzzy_scores[m]) + 2
    plt.axvline(x=best_k, color=colors[i], linestyle='--', alpha=0.6,
                label=f'm={m} best k={best_k}')

plt.xlabel('Numero cluster (k)', fontsize=12)
plt.ylabel('Silhouette Score', fontsize=12)
plt.title('Fuzzy C-Means: Silhouette Analysis per Fuzziness (m)', fontsize=14)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# TABELLla riassuntiva
df_results = pd.DataFrame({
    'k': list(k_range),
    'm=1.2': fuzzy_scores[1.2],
    'm=1.5': fuzzy_scores[1.5],
    'm=2.0': fuzzy_scores[2.0],
    'm=2.5': fuzzy_scores[2.5]
})

print("\n RISULTATI COMPLETI:")
print(df_results.round(3))

# Migliori configurazioni
print("\n CONFIGURAZIONI OTTIMALI:")
for m in m_range:
    best_k_idx = np.argmax(fuzzy_scores[m])
    best_k = best_k_idx + 2
    best_score = fuzzy_scores[m][best_k_idx]
    print(f"m={m}: k={best_k} (silhouette={best_score:.3f})")

"""Visualizzazione del metodo Fuzzy-kmeans, attraverso l'assegnazione soft di ogni titolo ad un cluster; per renderlo comparabile utilizziamo la funzione argmax in modo da ottenere il valore unitario per il cluster con assegnazione maggiore."""

cntr, u, _, _, _, _, fpc = fuzz.cmeans(db_cluster.T, c=3, m=1.5, error=0.005, maxiter=300)

partition_hard = np.argmax(u, axis=0)

plt.figure(figsize=(10,6))
scatter = plt.scatter(db_cluster.iloc[:,0], db_cluster.iloc[:,1],
                     c=partition_hard, cmap='viridis', s=50, alpha=0.7)
plt.scatter(cntr[:,0], cntr[:,1], c='red', s=200, marker='X', label='Centroidi')
plt.colorbar(scatter)
plt.title(f'Fuzzy K-Means (FPC={fpc:.3f})')
plt.legend()
plt.show()

"""L'ulteriore analisi conferma che la partizione che si avvicina a suddividere in modo più corretto i titoli utilizza 3 cluster. Il valore fpc (fuzzy partition coefficient) rappresenta il grado di partizione da soft ad hard nei vari cluster. Il valore ottenuto è un buon indicatore di partizionamento dei titoli."""

# Dopo cmeans()
n_clusters_real = u.shape[0]
partition_hard = np.argmax(u, axis=0)

# DataFrame dinamico
df_memberships = pd.DataFrame(
    u.T,
    columns=[f'Cluster_{i}' for i in range(n_clusters_real)]
)
df_memberships['Hard_Cluster'] = partition_hard

print("Shape OK:", df_memberships.shape)
print(df_memberships.head())

# Dopo: df_memberships con Cluster_0...Cluster_5 e Hard_Cluster

# 1. Calcola Max Membership per ogni titolo
df_memberships['Max_Membership'] = df_memberships[[f'Cluster_{i}' for i in range(3)]].max(axis=1)

# 2. STATISTICHE riassuntive (la tua Tabella 5.12)
print("Tabella 5.12. Sintesi dei gradi di appartenenza massimi nel fuzzy K-means")
print("="*70)

stats = {
    'Max membership media': df_memberships['Max_Membership'].mean().round(3),
    'Numero titoli > 0.8': (df_memberships['Max_Membership'] > 0.8).sum(),
    'Numero titoli < 0.6': (df_memberships['Max_Membership'] < 0.6).sum()
}

for key, value in stats.items():
    print(f"{key}: {value}")

# 3. Tabella completa (come tesi/relazione)
tabella_512 = pd.DataFrame({
    'Statistica': list(stats.keys()),
    'Valore': list(stats.values())
})
print("\n", tabella_512)

# Assumendo:
# - db_parametri_cluster = DataFrame (righe=titoli, colonne=['Omega','Alpha','Beta','Nu'])
# - df_cluster['cluster'] = labels_ward (hard clustering)
# - ticker_list = lista ticker nell'ordine di db_cluster

# 1. Mappa ticker → cluster
df_parametri_con_cluster = db_parametri_cluster.copy()
df_parametri_con_cluster['cluster'] = df_cluster['cluster'].values  # Allinea ordine!

# 2. Calcola MEDIE GARCH per cluster
parametri_cluster = df_parametri_con_cluster.groupby('cluster')[['Omega','Alpha','Beta','Nu']].mean()
print("PARAMETRI GARCH MEDI per CLUSTER:")
print(parametri_cluster.round(6))

# 3. Lista TITOLI per cluster + loro parametri
for c in range(3):
    titoli_cluster = df_parametri_con_cluster[df_parametri_con_cluster['cluster']==c].index
    print(f"\nCluster {c} ({len(titoli_cluster)} titoli):")
    print(titoli_cluster.tolist())
    print(df_parametri_con_cluster[df_parametri_con_cluster['cluster']==c][['Omega','Alpha','Beta','Nu']].round(4))

"""Dopo la valutazione col metodo soft, abbiamo una buona suddivisione dei titoli con la metà che mostrano un valore di 28 titoli con valore maggiore di 0.8, e solo un titolo con valore minore di 0.6."""
